### ISSUE TITLE
Filter by scope returning incorrect variable lists

### ISSUE THREAD

**Issue by thartshorne** [fragilefamilieschallenge/metadata_api#35] opened 2018-05-07 15:17 UTC
Using filter with scope = 2 returns incorrect results, returning a list of all variables with scope = 2 OR scope = 20. Filtering for scope = 2 returns 14274  variables while there should only be 24. Filtering by scope = 20 returns an object of 14250, which is correct. 

This issue persists with any substring of expected filters, e.g filtering by type = b returns same result as type = bin. 

Issue found by Ryan Vinh during R package testing.

**Comment by msalganik** [comment] 2018-05-07 18:31
Thanks @thartshorne and @rvinh.  I'm so happy this testing is turning up errors.

I'm assigning this issue to @vineetbansal.  Right now he is migrating us over to a new server and the Python 3 so it might be a while before he can address it.  cc @katejaeger

**Comment by vineetbansal** [comment] 2018-05-10 15:58
It looks like this is not a bug, but things are behaving at they were designed. As per documentation in the code (and the way it's implemented), the 'filter' and 'search' methods both "search database for variable names where field matches value at least partially". So 14274 is the correct number of results for this call, which translates to the user asking "show me all variables where there is a '2' somewhere in the 'scope' attribute".

If there is no way to do an exact search (seems to me there isn't), then we should add one, or otherwise think of simplifying this select/search/filter thing, which is indeed a little confusing.

**Comment by vineetbansal** [comment] 2018-06-06 15:08
Closing this as things work the way they were programmed. API Simplification issues can be handled separately in #13

**Closed by vineetbansal** 2018-06-06 15:08 UTC
